@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWJyZV91c3VhcmlvIjoianNhbnRvcyIsImNvcnJlbyI6Imphdmllci5zYW50b3NAZ21haWwuY29tIiwiaWF0IjoxNzgxOTI5MTU2LCJleHAiOjE3ODE5MzAwNTZ9.kEbFLfrDRrEmp-hfkrSsY2YPwX9zSkUEFCLrGk7ADw4

###
GET http://localhost:3000/api/games/ HTTP/1.1

###
GET http://localhost:3000/api/games/2 HTTP/1.1

###
POST http://localhost:3000/api/games/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "titulo": "The Legend of Zelda: Breath of the Wild",
    "genero": "Aventura",
    "descripcion": "Un juego de mundo abierto épico de Nintendo.",
    "studio_id": 6
}

###
PUT http://localhost:3000/api/games/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "titulo": "The Legend of Zelda: Tears of the Kingdom",
    "genero": "Aventura",
    "descripcion": "La secuela de Breath of the Wild.",
    "studio_id": 1
}

###
DELETE http://localhost:3000/api/games/1 HTTP/1.1
Authorization: Bearer {{token}}
